version: '3'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    expose:
      - "3000"
    env_file: .env
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - ./:/srv
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "1443:1443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/localhost.crt:/etc/nginx/localhost.crt
      - ./docker/localhost.key:/etc/nginx/localhost.key
      - ./docker/dhparam.pem:/etc/nginx/dhparam.pem
    depends_on:
      - app
  postgres:
    image: postgres:11.6
    expose:
      - "5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mailcatcher:
    image: kiesia/mailcatcher:latest
    ports:
      - "1080:1080"
    expose:
      - "1025"

volumes:
  postgres_data:
