default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] %>
  port: <%= ENV["POSTGRESQL_PORT"] %>

development:
  <<: *default
  database: auth_development

test:
  <<: *default
  database: auth_test
